#Práctica 1.1 — Probabilidad y Estadística 
#Análisis de la evolución poblacional mundial 

"""
Objetivo 

Utilizar un conjunto de datos real para comprobar el funcionamiento del entorno de análisis de datos y aplicar 
medidas estadísticas descriptivas básicas utilizando Pandas y NumPy.
"""

#Actividad 1 — Identificación de la fuente 
## Procedencia de los datos
Los datos utilizados en esta práctica provienen de **Our World in Data (OWID)**. La fuente original del conjunto de datos corresponde a **United Nations, World Population Prospects (2024)**.

## Cita de la fuente
> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

#Actividad 1 — Identificación de la fuente 
## Procedencia de los datos
Los datos utilizados en esta práctica provienen de **Our World in Data (OWID)**. La fuente original del conjunto de datos corresponde a **United Nations, World Population Prospects (2024)**.

## Cita de la fuente
> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

#Repuestas
Responde brevemente: 

¿Quién produjo originalmente los datos? Organización de las Naciones Unidas a través de su publicación World Population Prospects

¿Qué organización los procesa para su utilización en Our World in Data? Our World in Data (OWID)

¿Qué representa la variable que analizarás? Representa el cambio anual o crecimiento proyectado de la población hasta el año 2100 por país o región

In [1]:
#Actividad 2 — Carga y exploración de datos 
import pandas as pd
import numpy as np

# para cargar un archivo
df=pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

df.head() #LOS PRIMEROS 5

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [2]:
#Filas y columnas
df.shape

(38400, 5)

In [3]:
#Nombres de las columnas
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [4]:
#Para ver los tipos de datos 
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [5]:
#Para ver las columnas mejor descritas o mejor resumidas
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [6]:
#Valores faltantes 
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [7]:
#Cuantas enteidades son
df["Entity"].nunique()

256

1.	¿Cuántas filas y columnas tiene el dataset? 39562, 7
2.	¿Qué tipo de datos contiene la variable Year?int64
3.	¿Existen valores faltantes? si
4.	¿Cuántas entidades diferentes contiene el dataset? 262

In [8]:
#Para que te de una estructura de un DATAFRAME
df_year = df[["Year"]]
df_year.head()

   Year
0  1951
1  1952
2  1953
3  1954
4  1955

In [9]:
#Filtrar filas
df_extraccion_filas = df[df["Year"]== 2020]
df_extraccion_filas.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [10]:
df_2020mex = df [(df["Year"]==2020) & (df["Code"] == "MEX")]
df_2020mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [11]:
#RANGO DE FECHA DESDE EL AÑO EN QUE NACIMOS HASTA EL 2020
df_2006_2020_mex = df [(df["Year"] >= 2006) & (df["Year"] <= 2020) & (df["Code"] == "MEX")]
df_2006_2020_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN
22259,Mexico,MEX,2010,1624178.0,NaN

In [12]:
#Extraccion de los rangos de unicamente de las entidades mensionadas
df_extraccion_rango_mex_EYA=df_2006_2020_mex [["Entity","Year","Annual change in population"]]
df_extraccion_rango_mex_EYA

       Entity  Year  Annual change in population
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [14]:
df.loc[:,["Entity","Year"]]

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [ ]:
df.iloc[:,0:2]

            Entity Code
0      Afghanistan  AFG
1      Afghanistan  AFG
2      Afghanistan  AFG
3      Afghanistan  AFG
4      Afghanistan  AFG
...            ...  ...
38395     Zimbabwe  ZWE
38396     Zimbabwe  ZWE
38397     Zimbabwe  ZWE
38398     Zimbabwe  ZWE
38399     Zimbabwe  ZWE

[38400 rows x 2 columns]

In [ ]:
df.iloc[30:35,0:12]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN

In [ ]:
df.iloc[30:35,0:12]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN

In [ ]:
df.loc[:,["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [15]:
df.loc[10000,["Entity","Year","Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [ ]:
df.loc[(df["Year"] == 2020) & (df["Entity"] == "Mexico")]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [16]:
df.iloc[:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [17]:
df.iloc[["0", "2", "3"]]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN

In [18]:
df.iloc[0:4, 0:4]

        Entity Code  Year  Annual change in population
0  Afghanistan  AFG  1951                     103163.0
1  Afghanistan  AFG  1952                     108441.0
2  Afghanistan  AFG  1953                     108919.0
3  Afghanistan  AFG  1954                     111251.0

In [19]:
df_L = df [(df["Year"] >= 2006) & (df["Year"] <= 2023) & (df["Entity"]=="Lithuania")]
df_L.head

<bound method NDFrame.head of           Entity Code  Year  Annual change in population  \
19855  Lithuania  LTU  2006                     -52455.0
19856  Lithuania  LTU  2007                     -38431.0
19857  Lithuania  LTU  2008                     -32896.0
19858  Lithuania  LTU  2009                     -35227.0
19859  Lithuania  LTU  2010                     -65534.0
19860  Lithuania  LTU  2011                     -69079.0
19861  Lithuania  LTU  2012                     -40308.0
19862  Lithuania  LTU  2013                     -29975.0
19863  Lithuania  LTU  2014                     -25188.0
19864  Lithuania  LTU  2015                     -27400.0
19865  Lithuania  LTU  2016                     -36662.0
19866  Lithuania  LTU  2017                     -39792.0
19867  Lithuania  LTU  2018                     -26832.0
19868  Lithuania  LTU  2019                      -7428.0
19869  Lithuania  LTU  2020                        709.0
19870  Lithuania  LTU  2021                      -1276.0
19871  Lithuania  LTU  2022                      22433.0
19872  Lithuania  LTU  2023                      37181.0

       Annual population change (Projected)
19855                                   NaN
19856                                   NaN
19857                                   NaN
19858                                   NaN
19859                                   NaN
19860                                   NaN
19861                                   NaN
19862                                   NaN
19863                                   NaN
19864                                   NaN
19865                                   NaN
19866                                   NaN
19867                                   NaN
19868                                   NaN
19869                                   NaN
19870                                   NaN
19871                                   NaN
19872                                   NaN  >

In [ ]:
df_ext_EYA.mean(numeric_only=True)

Actividad 3 — Estadística descriptiva

In [24]:
df_historico = df.loc[df["Year"] == 2020]

col = df_historico["Annual change in population"]

mean = col.mean()
print("1.	¿Cuál es el valor de la media?", mean)

mediana = col.median()
print("2.	¿Cuál es el valor de la mediana?", mediana)

desviacion_estandar = col.std()
print("3.	¿Cuál es el valor de la desviación estándar?", desviacion_estandar)

minimo = col.min()
maximo = col.max()
print("4.	¿Qué entidad presenta el valor mínimo y cuál el máximo? Maximo: ", maximo,("Minimo: "), minimo)

1.	¿Cuál es el valor de la media? 2124908.84765625
2.	¿Cuál es el valor de la mediana? 34293.5
3.	¿Cuál es el valor de la desviación estándar? 9522989.815761836
4.	¿Qué entidad presenta el valor mínimo y cuál el máximo? Maximo:  75707590.0 Minimo:  -494016.0

Actividad 4 — Comprobación del entorno

In [25]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2