In [12]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [ ]:
#Que buscque la cadenas de texto que comiencen con tal letra
#Sirve para cambiarle el nombre a la columna "entity" y que ahora se llame "Pais" en tu tabla de datos.
df.rename(columns={"entity": "Pais"}, inplace=True)

In [10]:
df.head()

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [5]:
df.set_index("Pais")

            code  year  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [ ]:
#Sirve para convertir la columna "Pais" en el identificador principal (índice) de las filas de tu tabla
df.set_index(["code","year"])

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [ ]:
#Te lanza todos los nulos que hay en code
df.loc[df["code"].isnull()]

                                        Pais code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [ ]:
#RECARGUE EL DATASET porque lo converti en un indeice de filas entity 
df.loc[df["code"].notnull(),["entity","year","life_expectancy_0"]].head(3)

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [16]:
#Para borrar los valores nulos que hay en code
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity               0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [17]:
df.shape

(20217, 4)

In [ ]:
#Calcular el promedio de esperanza de vida por cada país o entidad (entity), ordenarlos de menor a mayor y quedarse con los valores más bajos.
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [22]:
#
promedio_pais = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

print("Promediio de esperanza de vida por pais", promedio_pais)

Promediio de esperanza de vida por pais entity
Monaco           78.05
San Marino       78.00
Andorra          77.99
Guernsey         77.00
Liechtenstein    76.29
                 ...
Niger            44.19
Mali             43.76
Sierra Leone     43.19
South Sudan      37.84
USSR             32.70
Name: life_expectancy_0, Length: 247, dtype: float64